language: generic
# sudo: required
services:
  - docker

before_install:
  - docker build -t irishman/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true irishman/react-test npm test

after_success:
  - docker build -t irishman/multi-client ./client
  - docker build -t irishman/multi-nginx ./nginx
  - docker build -t irishman/multi-server ./server
  - docker build -t irishman/multi-worker ./worker
  # Log in into docker-cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push irishman/multi-client
  - docker push irishman/multi-nginx
  - docker push irishman/multi-server
  - docker push irishman/multi-worker